v2
home-assistant-libs/forecast_solar pull request #13
Opened 2021-07-20 23:00 UTC by balloob

- Don't convert to kW / kWh but leave data as we get it from API
- Fix bug calculating difference by resetting `last_value` to 0 when calculating diffs
- Create re-usable methods to back properties
- Add tests

2021-07-21 14:37 UTC, frenck requested changes
We should rename the `kwh*` variables to `wh*`, just to prevent confusion for the future

2021-07-21 16:07 UTC, balloob commented
Done.

2021-07-21 17:46 UTC, frenck approved these changes
Nice! 👍

2021-07-21 17:46 UTC, merged

2021-07-22 02:44 UTC, MartinHjelmare commented on tests/test_models.py
> +    print("NOW", estimate.now())
Leftover debug print?

2021-07-22 06:01 UTC, balloob commented on tests/test_models.py
> +    print("NOW", estimate.now())
a320a9f