add validation methods
home-assistant-libs/forecast_solar pull request #41
Opened 2024-03-19 12:54 UTC by bj00rn

Add methods for validation to support validation of parameters in home assistant config flow to avoid creating broken sensors

* validate api key
* validate plane

2024-03-19 13:19 UTC, bj00rn commented
https://github.com/home-assistant/core/issues/106771

2024-03-19 13:54 UTC, bj00rn commented
Seems that `{api_key}/info` endpoint does not provide response `code` when `401` is returned for an invalid key, this causes an exception to be thrown in https://github.com/home-assistant-libs/forecast_solar/blob/171deff67b95e80605806e3db4800e4a01ceddb6/forecast_solar/exceptions.py#L29 when key is invalid. I've just tested with a nonsense key `aaaaaaaaaaaaaaaa` though som maybe results may vary dependending if the key is well formatted or not.

Maybe it's worth into making `code` optional for exceptions

2024-03-21 13:37 UTC, bj00rn commented
Depends on Please merge https://github.com/home-assistant-libs/forecast_solar/pull/43 for linting errors

2024-04-01 09:46 UTC, bj00rn commented
@frenck @MartinHjelmare rebased now, tests are passing

2024-04-02 09:29 UTC, klaasnicolaas requested changes

2024-04-02 09:29 UTC, klaasnicolaas commented on forecast_solar/__init__.py
> +    async def validate_plane(self):
```suggestion
    async def validate_plane(self) -> bool:
```

2024-04-02 09:29 UTC, klaasnicolaas commented on forecast_solar/__init__.py
> +    async def validate_api_key(self):
```suggestion
    async def validate_api_key(self) -> bool:
```

2024-04-02 11:10 UTC, bj00rn commented on forecast_solar/__init__.py
> +    async def validate_plane(self):
fixed

2024-04-02 11:10 UTC, bj00rn commented on forecast_solar/__init__.py
> +    async def validate_api_key(self):
fixed

2024-04-07 09:55 UTC, bj00rn commented
@klaasnicolaas any chance of getting this merged soon? I Need this to resolve https://github.com/home-assistant/core/issues/106771

2024-04-08 09:50 UTC, bj00rn commented on forecast_solar/__init__.py
> +        await self._request("info", False)
fixed

2024-04-08 10:14 UTC, klaasnicolaas approved these changes

2024-04-08 10:14 UTC, merged

2024-04-08 10:40 UTC, bj00rn commented
@klaasnicolaas Thanks! Will you carve a new release with this fix?

2024-04-08 11:14 UTC, klaasnicolaas commented
@bj00rn Yes, release v3.1.0 is now available.