Allow usage of the "adjust forecast" feature
home-assistant-libs/forecast_solar pull request #63
Opened 2024-06-20 20:48 UTC by GreenOpposite

This adds the "actual" query parameter to the estimate method, needed to use forecast.solars "adjust forecast" feature.
This as a first towards implementing [this feature request](https://community.home-assistant.io/t/forecast-solar-optional-send-data-in-get-requests/629216).

2024-06-20 21:24 UTC, klaasnicolaas requested changes
`actual` can be added to the params and does not need to be added to the end of the url.

2024-08-13 07:04 UTC, ximex commented
any updates to this PR when this PR is planed to get merged/released?

2024-08-13 07:08 UTC, klaasnicolaas commented
When all the CI checks are passing 😉 It needs to add tests for full pytest coverage

./Klaas

2024-08-13 07:40 UTC, ximex commented
@GreenOpposite could you check that? I'm not a python dev

2024-08-13 10:38 UTC, GreenOpposite commented
When I run the tests locally, everything passes and I get a code coverage of 95%, but the automatic test on GitHub fail to run with the error `Error: Codecov token not found. Please provide Codecov token with -t flag.`

2024-08-15 11:21 UTC, GreenOpposite commented
After a bit of investigation, it seems like what's happening is that the Codecov GitHub integration needs a token that my forked repository is missing. A maintainer has to approve the workflows for them to run in the context of this repository. @klaasnicolaas

2024-09-04 17:56 UTC, GreenOpposite commented
Any updates on the state of this PR? Do I need to do something? @klaasnicolaas

2024-09-09 17:32 UTC, klaasnicolaas commented
What I'm wondering is whether we should pass the `actual` parameter with every request by default (if you have an API key), or only when the value is higher than 0. 

The only thing I'm missing is a test that tests what happens if you specify a value higher than 0.

./klaas

2024-09-16 14:22 UTC, GreenOpposite commented
A value of `0` is also used to signal invalidation/reset of the previously send correction data. So not passing an `actual` value to the `estimate()` function has the effect of deactivating the correction.
```python
a = estimate()
b = estimate(actual=15)
c = estimate()
```
If you don't send `0` every time, then `a` and `c` would have different values, which I would argue is not intuitive.

What kind of testing is missing exactly?

2024-09-16 15:10 UTC, klaasnicolaas requested changes
A test where the `actual` is given a value higher than 0 and has an apikey. It may not be needed for the codecov, but then it is fully tested.

2024-09-16 15:52 UTC, klaasnicolaas commented
Another thing I was wondering: suppose someone has solar panels in 2 zones and therefore also a split forecast.solar, to what extent will this have an effect if you send the full actual of both zones together (because you often have that as an entity) every time. 🤔 

./Klaas

2024-09-17 17:23 UTC, klaasnicolaas requested changes
I think we should send float values ​​and these values ​​are a bit more realistic

2024-09-17 18:11 UTC, GreenOpposite commented on tests/test_models.py
> +    forecast: Estimate = await forecast_key_client.estimate(actual=5800)
True 🙃. Those values make a lot more sense!

2024-09-17 18:15 UTC, GreenOpposite commented
> Another thing I was wondering: suppose someone has solar panels in 2 zones and therefore also a split forecast.solar, to what extent will this have an effect if you send the full actual of both zones together (because you often have that data as single entity) every time. 🤔
> 
> ./Klaas

I think that might lead to wrong values being predicted, but I also don't see how that could be easily mitigated. You would need separate data for each zone and send the appropriate data with each request.

2024-10-03 13:07 UTC, klaasnicolaas approved these changes

2024-10-03 13:45 UTC, merged

2024-10-16 11:48 UTC, dennisreimann commented
Will this be supported/used in the HA integration?